#This is a pipeline to provision a new appservice plan as well as webapp service

trigger: none

pool: Default
  # vmImage: ubuntu-latest

stages:
  - stage: DeployingAppService
    jobs: 
     - job: AppService
       steps:
          - task: AzureCLI@2
            displayName: Creating AppServicePlan
            inputs:
              azureSubscription: 'Azure subscription 1(7a11095f-a846-497e-bfd1-accc49689b9c)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az appservice plan create --name   appservice-plan1 --resource-group abn-rg --is-linux'
   
          - task: AzureCLI@2
            displayName: Creating AppService
            inputs:
              azureSubscription: 'Azure subscription 1(7a11095f-a846-497e-bfd1-accc49689b9c)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az webapp create --resource-group abn-rg --plan appservice-plan1 --name webappservicetest1 --deployment-container-image-name nginx'
 