# This is a pipeline for starting web app service in azure

trigger: none


pool: Default
  # vmImage: ubuntu-latest
stages:
  - stage: startAppService
    jobs:
      - job: startJob
        steps:
        - task: AzureCLI@2
          displayName: Start WebApp Service
          inputs:
            azureSubscription: 'Azure subscription 1(7a11095f-a846-497e-bfd1-accc49689b9c)'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: 'az webapp start --name webappservicetest1 --resource-group abn-rg'


